### ISSUE TITLE
Symfony lock on 2.6.*

### ISSUE THREAD

**Issue by robfrawley** [headzoo/polymer-bundle#1]
Can you please change your composer.json file to allow for a rational symfony constraint. I don't know why it is explicitly `2.6`, but if, perhaps you are relying on features, specific to that release, a constraint of `>=2.6` or even (though I'd prefer not) `~2.6,>=2.6` would be much more appropriate.

I'd really like to use this bundle in a few projects, and forking it simply to change the composer constraint (and then having to make sure I'm keeping my fork up to date with your upstream repo) seems...like a waste of time, and generally useless exercise. ;-)

BTW: This thing looks amazing, and from playing around with it on a fresh install of 2.6 (just to see how it behaved), it's a solid implementation.

**Comment by robfrawley** [comment]
To clarify, I'm using `2.7` on all my projects and _testing_ the mainline `2.8` and `3.0` branches, hence the inability to use your bundle with its composer constraint set as it is.

**Comment by headzoo** [comment]
I set the version constraint to >=2.6, but haven't tested above 2.6. You'll have to let me know if something breaks, because the bundle does dig into some of Symfony's internals, which may have changed after 2.6.

**Comment by robfrawley** [comment]
Wonderful! There should not be any issues (BC breaks) until (maybe) 3.0, depending on the exact internals your using; but Fabian and the core team are generally really good at providing deprecation layers to support backwards compatibility, so I don't foresee any issues at the moment.

That said, I will absolutely let you know if/when I find anything that could be problematic in the next major release. I'm generally running the bleeding edge of Symfony: I'll try to act as the "try and break it on early releases" contributor. ;-)

Thanks again.

**Comment by laytoneverson** [comment]
The Symfony2 team promises BC throughout the minor releases of the framework. None of the methods being removed from the api will actually be removed until 3.0.

http://symfony.com/doc/current/contributing/code/bc.html   

This issue could be closed now @robfrawley, no?

**Comment by robfrawley** [comment]
@laytoneverson: Absolutely, this was fixed by @headzoo on the 14th of last month. All is good on my end! :-)

**Comment by laytoneverson** [comment]
@robfrawley, I'm not 100% sure if I'm correct about this or not but you can close the issue?

**Comment by robfrawley** [comment]
Sure. ;-)
